### ISSUE TITLE
The library could not compile for strict typescript from version >4.9.5

### ISSUE THREAD

**Issue by thomas-tran** [proximax-storage/tsjs-xpx-chain-sdk#151]
1. Error during build
RemoveExchangeOfferTransaction.ts:77:12
MosaicDefinitionTransaction.ts:131:12
ModifyMultisigAccountTransaction.ts:132:12
ExchangeOfferTransaction.ts:77:12
AccountAddressRestrictionModificationTransaction.ts:111:12
error TS2742: The inferred type of 'toJSON' cannot be named without a reference to '.pnpm/github.com+proximax-storage+tsjs-xpx-chain-sdk@81ef4207959a45cb376c7c0facd4f078be8c06b1/node_modules/tsjs-xpx-chain-sdk'. This is likely not portable. A type annotation is necessary.

2. Steps to reproduce the problem.
- Reference tsjs-xpx-chain-sdk#next to other project
- Set declaration = true in the tsconfig.json 
  "compilerOptions": {
    ...
    "declaration": true, 
   ... }
- Execute command pnpm/npm run build
- Unable to build project

3. Specifications like the version of the project, operating system, or hardware.
NodeJS: 18+
Typescript: >4.9.5

**Comment by sleepyOwl14** [comment]
the issue have been fixed.

Tested with 
NodeJS: 18.15.0
Typescript: 5.2.2
