### ISSUE TITLE
Update wiki & examples to use tsjs-xpx-chain-sdk

### ISSUE THREAD

**Issue by grd888** [proximax-storage/tsjs-xpx-chain-sdk#55]
Hi,

In the documentation page "Installation from github" , Dependencies section, it says Install _**java-xpx-chain-sdk**_ which I believe should be Install _**js-xpx-chain-library.**_ 

https://github.com/proximax-storage/tsjs-xpx-chain-sdk/wiki/Installation-from-github

Am I correct ? I can make a pull request with the corrections, if you want.

**Comment by yaaccount** [comment]
Actually, it is the other way around. Just tsjs-xpx-chain-sdk should be used, other libraries and names are outdated. I am working on the improvement.

Thanks for reporting, though.

**Comment by grd888** [comment]
I see. I did follow the instructions and installed the js library so will just remove it. Thanks for clarifying.

**Comment by yaaccount** [comment]
Updated the examples to work with recent network setup. Added more examples for complex scenarios - aggregate complete/bonded, secret lock/proof (cross-chain swap).
