### ISSUE TITLE
NetworkCurrencyMosaic namespaceId is wrong

### ISSUE THREAD

**Issue by sleepyOwl14** [proximax-storage/tsjs-xpx-chain-sdk#56]
Please fix NetworkCurrencyMosaic namespace Id, it is suppose to be `prx.xpx`.

Currently still following NEM `cat.currency`

**Comment by yaaccount** [comment]
I'll change it to match proximax mainnet, but I am not convinced it is the right action - IMO that class doesn't belong to the sdk and should not be exported at all. Proper place for this would be the application configuration. Network currency mosaic is chain specific and thus sdk should be agnostic to it - even if we agree that default namespace for network currency mosaic in sirius chain variants is "prx.xpx", other properties (divisibility, mutability, transferability, supply) can be different for other chains.

**Comment by sleepyOwl14** [comment]
yes, I agree. I think this class properties should be configurable in some way. 

Well, it is really urgent to update it as people starting to use the SDK and it will be huge inconvenient for them to convert the amount manually without createRelative and createAbsolute method 

Thanks
