### ISSUE TITLE
ModifyMetadataTransaction Issue

### ISSUE THREAD

**Issue by donhieu123** [proximax-storage/tsjs-xpx-chain-sdk#58]
const mosaicId = new MosaicId([123123,123123]);
    const modification = new MetadataModification(
      MetadataModificationType.ADD,
      "key",
      "value"
    );
    const tx = ModifyMetadataTransaction.createWithMosaicId(
      NetworkType.TEST_NET,
      Deadline.create(),
      mosaicId,
      [modification],
      new UInt64([0,0])
    )
    JSON.stringify(tx);

I created a transaction like above and issue was happen. It's seem to be unimplemented ModifyMetadataTransaction in file SerializeTransactionToJSON.

**Comment by yaaccount** [comment]
There are more tx types (the new ones) missing, I wonder why nobody complained until now ;)

https://github.com/proximax-storage/tsjs-xpx-chain-sdk/blob/master/src/infrastructure/transaction/SerializeTransactionToJSON.ts
