### ISSUE TITLE
I can not capture the Listener error, when the connection to the websocket fails

### ISSUE THREAD

**Issue by rjperaza** [proximax-storage/tsjs-xpx-chain-sdk#6]
I have a connection to websocket, I tried it in different ways and I did not succeed.

I tried it with catch, catch error, try catch and with none of these ways I succeeded

I attach the reference image!

**Comment by yaaccount** [comment]
Closing because it is most likely not relevant any longer. @rjperaza Please check and either re-open or create a new issue if necessary.
