### ISSUE TITLE
Missing MODIFY_ACCOUNT_METADATA in CreateTransactionFromPayload.js

### ISSUE THREAD

**Issue by joseabril25** [proximax-storage/tsjs-xpx-chain-sdk#64]
Problem: One of our InnerTransactions have a ModifyMetadataTransaction and using AggregateComplete and sign and recreate the transaction, it returns an transaction type not implemented yet. 

Findings: I checked the dist/src/infrastructure/transaction/CreateTransactionFromPayload.js and in the CreateTransaction() function the switch-case does not have the MODIFY_ACCOUNT_METADATA.

Steps to reproduce the problem:
Do an aggregate complete transaction and use metadata modification as one of the inner transactions.

**Comment by yaaccount** [comment]
AC: all known transaction types can be re-created from payload (all the "new ones" are missing now)
