### ISSUE TITLE
Validate address

### ISSUE THREAD

**Issue by Sotatek-CongNguyen** [proximax-storage/tsjs-xpx-chain-sdk#73]
Can I use SDK library to validate an unused address?
I try to use "getAccountInfo" but I can not found it if this address wasn't used.

**Comment by yaaccount** [comment]
There is a RawAddress.isValidEncodedAddress(<string>) method - it verifies that the checksum encoded in the address string is valid.

For this kind of questions please use telegram groups like https://t.me/proximax_devs or https://t.me/proximaxhelpdesk.
