### ISSUE TITLE
Websocket BlockInfo

### ISSUE THREAD

**Issue by st-wong** [proximax-storage/tsjs-xpx-chain-sdk#82]
When using websocket, `newBlock()` returns `undefined` for `numTransactions`, when it should return a number.

**Comment by yaaccount** [comment]
This information is not returned over the websocket from the server (incomplete data is received from websocket for blocks). To verify:
1) in your chrome browser open Developer tools -> Network
2) go to https://explorer.xpxsirius.io/#/, pick some live server
3) click on websocket connection, inspect incoming messages

In the network logs, you can see that the explorer app uses the websocket newblock only as a notification and queries the rest api for block details for each and every newblock received as a workaround.

You can try to report this issue to server/rest(?)
